### ISSUE TITLE
Additional dBFT phase

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/dbft#112]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when we don't have cool new features. We need to update our dBFT protocol for AMEV feature support.

## Describe the solution you'd like
* new phase must be optional
* it should follow the same logic as other payload exchanges, dBFT shouldn't care much about internals of exchanged data
* it needs additional tests (hi, #1, btw)

## Additional context
Blocked by #111.

**Comment by AnnaShaleva** [comment]
Closed by #118.
