### ISSUE TITLE
Refactor dBFT APIs

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/dbft#84]
## Is your feature request related to a problem? Please describe.
Some of dBFT APIs are not used since `WithNewBlockFromContext` addition. E.g. `WithGetConsensusAddress` always returns an empty address in NeoGo.

## Describe the solution you'd like
We need to review all unused dBFT APIs and remove them.

**Comment by AnnaShaleva** [comment]
Also implement https://github.com/nspcc-dev/dbft/pull/97#issuecomment-1973841163.

**Comment by roman-khimov** [comment]
That's mostly about setters, we want some set of `New*` and then interface would just expose the data to `dbft`. Setters are useless here, we never change these values except for initialization of a new payload (either generated one to send or received from the network).
