### ISSUE TITLE
Remove neo-go dependency

### ISSUE THREAD

**Issue by fyfyrchik** [nspcc-dev/dbft#87]
It is a circular dependency and sometimes lead to problems (I had some problems GOPROXY=direct after cleaning the cache)
We use only 2 packages from there:
`neo-go/pkg/io`: to serialize example messages. They are redefined in neo-go (protocol uses interfaces), so example messages can use any serialization scheme (json, gob, raw `encoding/binary` helpers, whatever).
`neo-go/pkg/util`: for `util.Uint*` numbers. For these generics could be used.

IMO example messages are still good, to use in tests or simulation.
Another option is embed this library to neo-go, but this is more costly.

**Comment by roman-khimov** [comment]
Duplicates #2. I'll reopen it, but it was never a problem to me.
